const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const cheerio=require('cheerio');
const {dependencies,wordpressInventory,evidenceDiff,remediationPatch}=require('../src/advanced');const {Store}=require('../src/store');const {pack,unpack,merge}=require('../src/backup');const {checkInventory,newMatches}=require('../src/watch');
test('dependency inventory excludes unpinned versions and separates ecosystems',()=>{
 assert.deepEqual(dependencies('requirements.txt','Django==4.2.1\nrequests>=2\n-e git+https://example.com\nfoo==1.0;python_version<"3"'),[{name:'django',version:'4.2.1',ecosystem:'PyPI'}]);
 assert.deepEqual(dependencies('composer.lock',JSON.stringify({packages:[{name:'a/b',version:'v1.2.3'},{name:'c/d',version:'dev-main'}]})),[{name:'a/b',version:'1.2.3',ecosystem:'Packagist'}]);
});
test('WordPress inventory does not attribute third party assets or treat missing versions as safe',()=>{
 const $=cheerio.load('<meta name="generator" content="WordPress 6.0"><script src="/wp-content/plugins/demo/a.js?ver=1.2"></script><link href="https://other.example/wp-content/themes/no/a.css"><script src="/wp-content/plugins/unknown/a.js"></script>');const rows=wordpressInventory($,'https://example.com');assert.equal(rows.length,3);assert.equal(rows[2].version,null);assert.ok(rows.every(r=>r.confidence.endsWith('unverified')));
});
test('evidence comparison preserves uncertainty when a check was skipped',()=>{const rows=evidenceDiff({findings:[{id:'a',title:'A',evidence:'old'}]},{findings:[],resolved:[{id:'a',status:'needs_verification'}]});assert.equal(rows[0].state,'needs_verification');assert.equal(rows[0].before,'old');});
test('backup authentication, restored authorization and conflict protection',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vexon-backup-'));const dest=fs.mkdtempSync(path.join(os.tmpdir(),'vexon-restore-'));try{const a=new Store(dir);const project=a.saveProject({name:'Test',url:'https://example.com',authorized:true,schedule:'daily',cveWatch:true});a.addChat(project.id,'user','test');const data=pack(a,'long-passphrase-123');assert.ok(!data.includes('example.com'));assert.throws(()=>unpack(data,'wrong-passphrase'));const parsed=unpack(data,'long-passphrase-123');const b=new Store(dest);assert.equal(merge(b,parsed),1);assert.equal(b.project(project.id).authorized,false);assert.equal(b.project(project.id).schedule,'off');assert.equal(b.chat(project.id)[0].text,'test');assert.throws(()=>merge(b,parsed),/ίδιο ID/);parsed.workspace.projects[0].id='../../bad';assert.throws(()=>unpack(pack(a,'long-passphrase-123').replace('vexon-backup-1','bad'),'long-passphrase-123'));}finally{fs.rmSync(dir,{recursive:true,force:true});fs.rmSync(dest,{recursive:true,force:true});}
});
test('CVE watch sends exact ecosystem and version, and refuses incomplete responses',async()=>{
 const inventory=[{name:'django',version:'4.2.1',ecosystem:'PyPI'}];let request;const result=await checkInventory(inventory,{fetchImpl:async(url,opts)=>{request=JSON.parse(opts.body);return {ok:true,json:async()=>({results:[{vulns:[{id:'TEST-1'}]}]})};}});assert.equal(request.queries[0].package.ecosystem,'PyPI');assert.equal(newMatches(result,result).length,0);assert.equal(newMatches(null,result).length,1);await assert.rejects(checkInventory(inventory,{fetchImpl:async()=>({ok:true,json:async()=>({results:[]})})}),/Ελλιπή/);
});
test('remediation produces a reviewable patch without executing changes',()=>{const patch=remediationPatch({findings:[{checkId:'nosniff',title:'Missing',recommendation:'Fix'}]});assert.match(patch,/new file mode 100644/);assert.match(patch,/X-Content-Type-Options/);assert.throws(()=>remediationPatch({findings:[]}),/Δεν υπάρχει/);});
test('second observation marks inconsistent HTTP evidence for review',async()=>{const {finding}=require('../src/findings');const f=finding('nosniff',{url:'https://example.com/',title:'Missing'});const report={findings:[f],coverage:[f.scope+'|nosniff'],errors:[]};await require('../src/verify').verifyObservations(report,{request:async()=>({status:200,headers:{'content-type':'text/html','x-content-type-options':'nosniff'},body:'<html></html>'})});assert.equal(f.verification.result,'inconsistent');assert.equal(f.kind,'needs_confirmation');assert.equal(report.coverage.length,0);});
