const fs=require('node:fs');const path=require('node:path');const {dialog,app}=require('electron');const {safeText}=require('../src/privacy');const sessions=new Map();
function parseCookies(text,url){if(new URL(url).protocol!=='https:')throw new Error('Το login scan απαιτεί HTTPS.');if(text.length>16000||/[\r\n]/.test(text))throw new Error('Μη έγκυρο cookie header.');return text.split(';').filter(s=>s.trim()).map(s=>{const at=s.indexOf('=');const name=s.slice(0,at).trim(),value=s.slice(at+1).trim();if(at<1||! /^[!#$%&'*+.^_`|~\w-]+$/.test(name)||/[\x00-\x20\x7f;,]/.test(value))throw new Error('Μη έγκυρο cookie.');return {name,value};});}
function sessionFor(project){const s=sessions.get(project.id);if(!s||s.origin!==new URL(project.url).origin||s.expires<Date.now()){sessions.delete(project.id);return null;}return s;}
function setupUpgrades({handle,store,win,isBusy,notify,emit,getProfile=()=>({}),restoreProfile=()=>{}}){
 handle('session:set',(id,text)=>{if(isBusy())throw new Error('Περίμενε τη σάρωση.');const p=store.project(id);if(!p.authorized)throw new Error('Απαιτείται άδεια ελέγχου.');if(!text){sessions.delete(id);return false;}const cookies=parseCookies(String(text),p.url);sessions.set(id,{context:require('node:crypto').randomUUID(),origin:new URL(p.url).origin,cookies,expires:Date.now()+3600000});return true;});
 handle('backup:export',async password=>{const data=require('../src/backup').pack(store,password,getProfile());const out=await dialog.showSaveDialog(win(),{defaultPath:'Vexon-backup.vexon',filters:[{name:'Vexon encrypted backup',extensions:['vexon']}]});if(out.canceled)return null;fs.writeFileSync(out.filePath,data,{mode:0o600});return out.filePath;});
 handle('backup:import',async password=>{if(isBusy())throw new Error('Περίμενε τη σάρωση.');const out=await dialog.showOpenDialog(win(),{properties:['openFile'],filters:[{name:'Vexon encrypted backup',extensions:['vexon']}]});if(out.canceled)return null;if(fs.statSync(out.filePaths[0]).size>100_000_000)throw new Error('Μέγιστο backup 100 MB.');const data=require('../src/backup').unpack(fs.readFileSync(out.filePaths[0],'utf8'),password);const count=require('../src/backup').merge(store,data);if(data.profile)restoreProfile(data.profile);return count;});
 handle('remediation:export',async id=>{const proposal=require('../src/advanced').remediationPatch(store.report(id));const out=await dialog.showSaveDialog(win(),{defaultPath:'Vexon-remediation.patch',filters:[{name:'Reviewable configuration patch',extensions:['patch']}]});if(out.canceled)return null;fs.writeFileSync(out.filePath,proposal);return out.filePath;});
 const watchBusy=new Set();async function watch(id){if(watchBusy.has(id))throw new Error('Έλεγχος CVE σε εξέλιξη.');watchBusy.add(id);try{const p=store.project(id);if(!p.authorized)throw new Error('Απαιτείται άδεια.');const last=store.history(id).map(r=>store.report(r.id)).find(r=>r.inventory?.length);if(!last)throw new Error('Εκτέλεσε πρώτα σάρωση repository με υποστηριζόμενο lockfile.');const mod=require('../src/watch');const result=await mod.checkInventory(last.inventory);store.data.watches||={};result.inventoryAt=last.completedAt;result.new=mod.newMatches(store.data.watches[id],result);store.data.watches[id]=result;store.commit();if(result.new.length)notify('Νέες αναφορές CVE · '+p.name,result.new.length+' αντιστοιχίσεις στην αποθηκευμένη απογραφή.');emit('watch:finished',{id,result});return result;}finally{watchBusy.delete(id);}}
 handle('watch:run',watch);handle('watch:get',id=>{store.project(id);return store.data.watches?.[id]||null;});
 let nextWatch=0;const timer=setInterval(async()=>{if(isBusy()||Date.now()<nextWatch)return;nextWatch=Date.now()+3600000;for(const p of store.list().filter(p=>p.authorized&&p.cveWatch)){try{if(Date.now()-Date.parse(store.data.watches?.[p.id]?.checkedAt||0)>=86400000)await watch(p.id);}catch(e){emit('watch:finished',{id:p.id,error:safeText(e.message)});}}},60000);app.on('before-quit',()=>clearInterval(timer));
 let updater;let updateState={status:'unconfigured',message:'Οι αυτόματες εγκαταστάσεις χρειάζονται signed release και publisherName στο build.'};
 try{const pkg=require('../package.json');if(app.isPackaged&&pkg.build?.win?.publisherName){updater=require('electron-updater').autoUpdater;updater.autoDownload=true;updater.autoInstallOnAppQuit=true;updater.on('error',e=>{updateState={status:'error',message:safeText(e.message)};emit('update:state',updateState);});for(const event of ['checking-for-update','update-available','update-not-available','update-downloaded'])updater.on(event,()=>{updateState={status:event};emit('update:state',updateState);});setTimeout(()=>updater.checkForUpdates().catch(()=>{}),30000);}}catch(e){updateState={status:'error',message:safeText(e.message)};}
 handle('update:check',async()=>{if(updater)await updater.checkForUpdates();return updateState;});
}
module.exports={setupUpgrades,sessionFor,parseCookies};
