const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('el-GR',{dateStyle:'short',timeStyle:'short'}):'—';
const statusLabel={complete:'Ολοκληρώθηκε',partial:'Μερική κάλυψη',failed:'Απέτυχε',cancelled:'Ακυρώθηκε',open:'Ανοιχτό',resolved:'Διορθώθηκε',needs_verification:'Επιβεβαίωση'};
const kindLabel={observed:'Παρατηρήθηκε',recommendation:'Σύσταση',needs_confirmation:'Πιθανό πρόβλημα'};
const titles={chat:'Ο βοηθός ασφαλείας σου',overview:'Η εικόνα των ιστοσελίδων σου',projects:'Ιστοσελίδες & πελάτες',history:'Ιστορικό σαρώσεων',schedules:'Προγραμματισμένοι έλεγχοι',settings:'Ρυθμίσεις χώρου εργασίας',report:'Αναφορά & επανέλεγχος'};
let state={projects:[],history:[],settings:{},busy:false};let activeReport=null;let toastTimer;
function toast(message,error=false){clearTimeout(toastTimer);$('#toast').hidden=false;$('#toast').classList.toggle('error',error);$('#toast').textContent=message;toastTimer=setTimeout(()=>$('#toast').hidden=true,9000);}
function show(id){$$('.view').forEach(v=>v.hidden=v.id!==id);$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#pageTitle').textContent=titles[id];}
function badge(status){return `<span class="badge ${esc(status)}">${esc(statusLabel[status]||status)}</span>`;}
function empty(title,text){return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(text)}</p></div>`;}
function projectCard(p){const last=p.lastReport;return `<article class="project-card"><div class="top"><div class="project-title"><span class="site-icon">◈</span><div><h3>${esc(p.name)}</h3><small>${esc(p.client||'Χωρίς πελάτη')}</small></div></div>${last?badge(last.status):'<span class="chip">Νέο έργο</span>'}</div><p class="domain">${esc(p.url)}</p><div class="chips"><span class="chip">HTTP / TLS</span>${p.browser?'<span class="chip">Chromium</span>':''}${p.repository?'<span class="chip">GitHub</span>':''}${p.schedule!=='off'?'<span class="chip green">'+(p.schedule==='daily'?'Καθημερινά':'Εβδομαδιαία')+'</span>':''}</div><div class="project-actions"><button data-scan="${p.id}" class="primary" ${state.busy?'disabled':''}>${last?'Επανέλεγχος':'Σάρωση'} →</button><button data-edit="${p.id}" class="subtle">Ρυθμίσεις</button>${last?`<button data-report="${last.id}" class="text-button">Αναφορά</button>`:''}</div>${p.nextRun?`<small class="help">Επόμενος έλεγχος: ${date(p.nextRun)}</small>`:''}</article>`;}
function historyTable(rows){if(!rows.length)return empty('Το ιστορικό ξεκινά με τον πρώτο έλεγχο','Οι αναφορές αποθηκεύονται αυτόματα στη συσκευή σου.');return `<div class="table-wrap"><table><thead><tr><th>ΙΣΤΟΣΕΛΙΔΑ</th><th>ΗΜΕΡΟΜΗΝΙΑ</th><th>ΚΑΤΑΣΤΑΣΗ</th><th>ΕΥΡΗΜΑΤΑ</th><th></th></tr></thead><tbody>${rows.map(r=>{const p=state.projects.find(p=>p.id===r.projectId);return `<tr><td><b>${esc(p?.name||r.target)}</b><small>${esc(p?.client||'')}</small></td><td>${date(r.completedAt)}</td><td>${badge(r.status)}</td><td>${r.summary.total}<small>${r.comparison?.resolved||0} διορθώθηκαν</small></td><td><button class="text-button" data-report="${r.id}">Αναφορά →</button></td></tr>`;}).join('')}</tbody></table></div>`;}
function render(){
  const chatSelected=$('#chatProject').value;$('#chatProject').innerHTML='<option value="">Επίλεξε ιστοσελίδα</option>'+state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#chatProject').value=chatSelected;

  const latest=state.projects.map(p=>p.lastReport).filter(Boolean);const open=latest.reduce((sum,r)=>sum+r.summary.total,0);const stats=[['Ιστοσελίδες',state.projects.length,'Σε έναν χώρο εργασίας'],['Τελευταία ευρήματα',open,'Από τις πρόσφατες αναφορές'],['Διορθώθηκαν',latest.reduce((n,r)=>n+(r.comparison?.resolved||0),0),'Επιβεβαιωμένα με επανέλεγχο'],['Αυτόματοι έλεγχοι',state.projects.filter(p=>p.schedule!=='off').length,'Όσο η εφαρμογή λειτουργεί']];
  $('#metrics').innerHTML=stats.map(([label,n,sub])=>`<div class="metric"><span>${label}</span><strong>${n}</strong><small>${sub}</small></div>`).join('');
  $('#recentProjects').innerHTML=state.projects.slice(0,4).map(projectCard).join('')||empty('Πρόσθεσε την πρώτη ιστοσελίδα','Σύνδεσε έναν πελάτη και ξεκίνα έναν έλεγχο.');
  const term=$('#projectSearch').value.toLowerCase();$('#projectList').innerHTML=state.projects.filter(p=>(p.name+' '+p.client+' '+p.url).toLowerCase().includes(term)).map(projectCard).join('')||empty('Δεν βρέθηκαν ιστοσελίδες','Πρόσθεσε μια ιστοσελίδα ή άλλαξε την αναζήτηση.');
  $('#recentHistory').innerHTML=historyTable(state.history.slice(0,5));
  const filter=$('#historyFilter').value;$('#historyFilter').innerHTML='<option value="">Όλες οι ιστοσελίδες</option>'+state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#historyFilter').value=filter;
  $('#historyList').innerHTML=historyTable(state.history.filter(r=>!filter||r.projectId===filter));
  $('#scheduleList').innerHTML=state.projects.filter(p=>p.schedule!=='off').map(projectCard).join('')||empty('Δεν έχουν οριστεί αυτόματοι έλεγχοι','Στις ρυθμίσεις μιας ιστοσελίδας επίλεξε κάθε 24 ώρες ή κάθε 7 ημέρες.');
}
async function refresh(){state=await window.vexon.workspace();render();}
function fillSettings(){const f=$('#settingsForm');for(const k of ['company','contact'])f.elements[k].value=state.settings[k]||'';for(const k of ['notifications','launchAtLogin'])f.elements[k].checked=Boolean(state.settings[k]);$('#apiKeyState').textContent=state.settings.hasApiKey?'Κλειδί αποθηκευμένο με κρυπτογράφηση.':'Δεν υπάρχει αποθηκευμένο κλειδί.';$('#githubKeyState').textContent=state.settings.hasGithubToken?'Token αποθηκευμένο με κρυπτογράφηση.':'Δημόσια repos λειτουργούν χωρίς token, με τα όρια του GitHub.';if(state.settings.logo)$('#brandLogo').src=state.settings.logo;}
function editProject(id){const p=state.projects.find(p=>p.id===id);const form=$('#projectForm');form.reset();form.elements.id.value=p?.id||'';$('#projectError').textContent='';$('#dialogTitle').textContent=p?'Ρυθμίσεις ιστοσελίδας':'Νέα ιστοσελίδα';if(p)for(const [k,v] of Object.entries(p)){const e=form.elements[k];if(e){if(e.type==='checkbox')e.checked=Boolean(v);else e.value=v??'';}}$('#projectDialog').showModal();}
async function scan(id){if(state.busy)return;state.busy=true;render();$('#scanProgress').hidden=false;try{const r=await window.vexon.scan(id);await refresh();renderReport(r);show('report');}catch(e){toast(e.message,true);}finally{state.busy=false;$('#scanProgress').hidden=true;render();}}
function renderReport(report){activeReport=report;const p=state.projects.find(p=>p.id===report.projectId)||{};
  $('#reportContent').innerHTML=`<div class="panel report-banner"><div class="score-ring"><strong>${report.summary.score??'—'}</strong><small>${report.summary.score===null?'ΧΩΡΙΣ ΒΑΘΜΟΛΟΓΙΑ':'/ 100 · ΡΥΘΜΙΣΕΙΣ'}</small></div><div><h2>${esc(p.name||report.target)}</h2><p>${esc(report.target)}</p><p>${date(report.completedAt)} · ${report.pagesScanned.length} σελίδες</p></div><div class="report-actions"><button class="primary" data-scan="${report.projectId}" ${state.busy?'disabled':''}>Έλεγχος ξανά</button><button class="secondary" data-export="pdf">Λήψη PDF</button><button class="subtle" data-export="json">JSON</button></div></div>
    <div class="report-summary">${badge(report.status)}<span class="chip">${report.comparison?.new||0} νέα</span><span class="chip green">${report.comparison?.resolved||0} διορθώθηκαν</span><span class="chip">${report.comparison?.unverified||0} ανεπιβεβαίωτα</span><span class="chip">${report.summary.counts.high+report.summary.counts.critical} υψηλής προτεραιότητας</span></div>
    <details class="panel coverage" ${report.errors.length?'open':''}><summary>Κάλυψη ελέγχου & περιορισμοί</summary><p>${esc(report.methodology)}</p><p>Η βαθμολογία δεν πιστοποιεί την ασφάλεια της ιστοσελίδας. Στη μερική κάλυψη ή αποτυχία δεν υπολογίζεται.</p><p>Browser: ${report.browser?.pages?.length||0} σελίδες · GitHub: ${report.source?.filesChecked||0} αρχεία · OSV: ${report.source?.packagesChecked||0} npm πακέτα</p>${report.source?.commit?`<p>GitHub commit: ${esc(report.source.commit)}</p>`:''}<ul>${report.errors.map(e=>`<li>${esc(e.module)}: ${esc(e.error)} ${esc(e.url||'')}</li>`).join('')}</ul></details>
    <div class="section-head"><h2>Ευρήματα & ενέργειες</h2></div><div class="report-filter"><select id="severityFilter" aria-label="Σοβαρότητα"><option value="">Όλες οι προτεραιότητες</option value="high">High / Critical</option value="medium">Medium</option value="low">Low</option value="info">Info</option></select><select id="statusFilter" aria-label="Κατάσταση"><option value="">Όλες οι καταστάσεις</option value="open">Ανοιχτά</option value="needs_verification">Επιβεβαίωση</option value="resolved">Διορθώθηκαν</option></select></div><label class="checkbox"><input id="cveOnly" type="checkbox"> Μόνο γνωστές ευπάθειες / CVE</label><div id="findingList" class="panel"></div><div class="section-head"><h2>Διαδικτυακή έρευνα CVE</h2></div><div class="panel padded">${(report.cveCandidates||[]).map(researchHtml).join('')||'Δεν έγινε αναζήτηση NVD σε αυτή τη σάρωση.'}</div>
    ${report.ai?`<div class="section-head"><h2>Συμπληρωματική AI ανάλυση</h2></div><div class="panel padded report-ai">${esc(report.ai.text||report.ai.error)}</div>`:''}`;
  renderFindings();$('#cveOnly').onchange=renderFindings;$('#severityFilter').onchange=renderFindings;$('#statusFilter').onchange=renderFindings;
}
function renderFindings(){const sev=$('#severityFilter').value;const status=$('#statusFilter').value;const all=[...activeReport.findings,...(activeReport.resolved||[])].filter(f=>(!$('#cveOnly').checked||f.checkId.startsWith('osv:'))&&(!sev||(sev==='high'?['high','critical'].includes(f.severity):f.severity===sev))&&(!status||f.status===status));
  $('#findingList').innerHTML=all.length?all.map(f=>`<article class="finding-card"><div class="finding-top">${badge(f.severity)}<span class="chip">${esc(kindLabel[f.kind]||f.kind)}</span>${f.change==='new'?'<span class="chip green">Νέο</span>':''}${f.status==='resolved'?badge('resolved'):`<select data-finding="${f.id}" aria-label="Κατάσταση ευρήματος"><option value="open" ${f.status==='open'?'selected':''}>Ανοιχτό</option><option value="needs_verification" ${f.status==='needs_verification'?'selected':''}>Χρειάζεται επιβεβαίωση</option></select>`}</div><h3>${esc(f.title)}</h3><div class="finding-url">${esc(f.url)}</div><p><b>Απόδειξη:</b> ${esc(f.evidence)}</p><p><b>Επόμενη ενέργεια:</b> ${esc(f.recommendation)}</p>${f.vulnerability?`<p><b>CVE:</b> ${esc(f.vulnerability.cves.join(', ')||'Δεν υπάρχει CVE alias')}<br><b>CVSS:</b> ${esc(f.vulnerability.cvss.join('; ')||'Δεν παρέχεται')}<br><b>Αντιστοίχιση:</b> ακριβής έκδοση εξάρτησης<br><b>Ανάκτηση:</b> ${esc(date(f.vulnerability.retrievedAt))}</p><button class="text-button" data-source="${esc(f.vulnerability.source)}">Επίσημη αναφορά OSV ↗</button>`:''}</article>`).join(''):empty('Δεν υπάρχουν ευρήματα σε αυτή την προβολή','Η απουσία ευρημάτων δεν αποτελεί πιστοποίηση ασφάλειας.');
}
$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#addProject').onclick=$('#heroAdd').onclick=()=>editProject();$('#closeDialog').onclick=()=>$('#projectDialog').close();$('#projectSearch').oninput=render;$('#historyFilter').onchange=render;
$('#projectForm').onsubmit=async event=>{event.preventDefault();const f=event.target;const p=Object.fromEntries(new FormData(f));for(const key of ['browser','useAI','authorized','wordpress','cveWatch'])p[key]=f.elements[key]?.checked||false;try{await window.vexon.saveProject(p);$('#projectDialog').close();await refresh();show('projects');toast('Η ιστοσελίδα αποθηκεύτηκε.');}catch(e){$('#projectError').textContent=e.message;}};
$('#settingsForm').onsubmit=async event=>{event.preventDefault();const f=event.target;const values=Object.fromEntries(new FormData(f));for(const key of ['notifications','launchAtLogin'])values[key]=f.elements[key].checked;try{await window.vexon.saveSettings(values);f.elements.apiKey.value='';f.elements.githubToken.value='';await refresh();fillSettings();toast('Οι ρυθμίσεις αποθηκεύτηκαν.');}catch(e){toast(e.message,true);}};
$('#pickLogo').onclick=async()=>{try{const logo=await window.vexon.pickLogo();if(logo)$('#brandLogo').src=logo;}catch(e){toast(e.message,true);}};
$('#cancelScan').onclick=async()=>{await window.vexon.cancel();$('#progressText').textContent='Ακύρωση και αποθήκευση αποτελεσμάτων…';};
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{if(b.dataset.source)await window.vexon.openSource(b.dataset.source);if(b.dataset.prompt){$('#chatInput').value=b.dataset.prompt;$('#chatForm').requestSubmit();}if(b.dataset.edit)editProject(b.dataset.edit);if(b.dataset.scan)await scan(b.dataset.scan);if(b.dataset.report){renderReport(await window.vexon.report(b.dataset.report));show('report');}if(b.dataset.export){b.disabled=true;try{const path=await window.vexon.exportReport(activeReport.id,b.dataset.export);if(path)toast('Η αναφορά αποθηκεύτηκε: '+path);}finally{b.disabled=false;}}}catch(e){toast(e.message,true);}});
document.addEventListener('change',async event=>{if(event.target.dataset.finding){try{const r=await window.vexon.status(activeReport.id,event.target.dataset.finding,event.target.value);activeReport=r;renderFindings();}catch(e){toast(e.message,true);}}});
window.vexon.onProgress(p=>{state.busy=p.stage!=='done';$('#scanProgress').hidden=!state.busy;$('#progressText').textContent=p.message;$('#progressBar').value=p.percent;if(p.stage==='done')refresh().catch(e=>toast(e.message,true));});
window.vexon.onFinished(async r=>{await refresh();toast('Αποθηκεύτηκε νέα αναφορά: '+(state.projects.find(p=>p.id===r.projectId)?.name||r.target));});
refresh().then(fillSettings).catch(e=>toast(e.message,true));

function researchHtml(research){return `<div class="research"><p><b>${esc(research.query)}</b> · ${esc(research.source)} · ${date(research.retrievedAt)}</p><p>${esc(research.note)}</p>${research.detected?`<p>Ένδειξη site: ${esc(research.detected.name)} ${esc(research.detected.version||'άγνωστη έκδοση')} — απαιτείται επαλήθευση.</p>`:''}${research.items.map(item=>`<article class="cve-card"><div class="finding-top"><b>${esc(item.id)}</b><span class="chip">${esc(item.severity)} · CVSS ${esc(item.score??'—')}</span><span class="chip">Υποψήφιο</span></div><p>${esc(item.description)}</p><button class="text-button" data-source="${esc(item.source)}">Πηγή NVD ↗</button></article>`).join('')||'<p>Δεν επιστράφηκαν αποτελέσματα. Αυτό δεν αποδεικνύει απουσία ευπαθειών.</p>'}</div>`;}
let chatEntries=[];
function renderChat(){const container=$('#chatMessages');container.innerHTML=chatEntries.length?chatEntries.map(m=>`<article class="chat-bubble ${m.role==='user'?'user':'assistant'}"><small>${m.role==='user'?'Εσύ':'Vexon'} · ${date(m.createdAt)}</small><div class="chat-text">${esc(m.text)}</div>${m.reportId?`<button class="secondary" data-report="${esc(m.reportId)}">Άνοιγμα αναφοράς</button>`:''}${m.research?researchHtml(m.research):''}</article>`).join(''):'<div class="chat-empty"><h2>Τι θέλεις να ελέγξουμε;</h2><p>Επίλεξε ιστοσελίδα και γράψε μια εντολή ή μια ερώτηση.</p></div>';container.scrollTop=container.scrollHeight;}
$('#chatProject').onchange=async()=>{try{chatEntries=$('#chatProject').value?(await window.vexon.chat($('#chatProject').value)).messages:[];renderChat();}catch(e){toast(e.message,true);}};
$('#chatForm').onsubmit=async event=>{event.preventDefault();const id=$('#chatProject').value;const text=$('#chatInput').value.trim();if(!id){toast('Επίλεξε πρώτα ιστοσελίδα από τη λίστα.',true);return;}if(!text)return;$('#chatInput').value='';$('#chatHint').textContent='Επεξεργασία μηνύματος…';try{await window.vexon.sendChat(id,text);}catch(e){toast(e.message,true);}finally{$('#chatHint').textContent='Μπορείς να ζητήσεις πρόοδο ή εξήγηση όσο τρέχει η σάρωση.';}};
window.vexon.onChat(({projectId,message})=>{if($('#chatProject').value===projectId){chatEntries.push(message);renderChat();}});
renderChat();
