let report=null; let settings={maxPages:10,useAI:true};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const titles={scanner:'Έλεγχος ασφαλείας',reports:'Αναφορά ασφαλείας',settings:'Ρυθμίσεις'};
function show(id){$$('.view,.nav').forEach(x=>x.classList.remove('active'));$(`#${id}`).classList.add('active');$(`.nav[data-view="${id}"]`).classList.add('active');$('#pageTitle').textContent=titles[id]}
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
window.vexon.onProgress(p=>{$('#progressText').textContent=p.message;$('#progressPct').textContent=`${p.percent}%`;$('#progressBar').style.width=`${p.percent}%`});
async function load(){settings=await window.vexon.getSettings();$('#maxPages').value=settings.maxPages||10;$('#useAI').checked=settings.useAI!==false;$('#keyState').textContent=settings.hasApiKey?'Υπάρχει αποθηκευμένο κρυπτογραφημένο κλειδί. Άφησέ το κενό για να διατηρηθεί.':'Δεν υπάρχει αποθηκευμένο κλειδί.'}load();
$('#saveSettings').onclick=async()=>{try{const apiKey=$('#apiKey').value.trim();settings=await window.vexon.saveSettings({apiKey:apiKey||undefined,maxPages:$('#maxPages').value,useAI:$('#useAI').checked});$('#saveMessage').textContent='Οι ρυθμίσεις αποθηκεύτηκαν με ασφάλεια.';$('#apiKey').value='';$('#keyState').textContent='Υπάρχει αποθηκευμένο κρυπτογραφημένο κλειδί.'}catch(e){$('#saveMessage').textContent=e.message}};
$('#scanForm').onsubmit=async e=>{e.preventDefault();const btn=$('#scanBtn');btn.disabled=true;btn.textContent='Σάρωση…';$('#progressCard').classList.remove('hidden');try{report=await window.vexon.scan({url:$('#target').value,authorized:$('#authorized').checked,maxPages:Number($('#maxPages').value||settings.maxPages||10),useAI:$('#useAI').checked});render(report);show('reports')}catch(err){alert(`Η σάρωση απέτυχε: ${err.message}`)}finally{btn.disabled=false;btn.textContent='Έναρξη σάρωσης →';$('#progressCard').classList.add('hidden')}};
function esc(x){const d=document.createElement('div');d.textContent=String(x??'');return d.innerHTML}
function render(r){$('#empty').classList.add('hidden');$('#report').classList.remove('hidden');$('#scoreValue').textContent=r.summary.score;$('#targetName').textContent=new URL(r.target).hostname;$('#scanMeta').textContent=`${r.pagesScanned.length} σελίδες • ${new Date(r.completedAt).toLocaleString('el-GR')}`;$('#severity').innerHTML=['critical','high','medium','low'].map(s=>`<div class="sev"><b>${r.summary.counts[s]}</b><small>${s}</small></div>`).join('');$('#findingTotal').textContent=`${r.summary.total} ευρήματα`;$('#findings').innerHTML=r.findings.length?r.findings.map(f=>`<article class="finding"><h3><span class="badge ${f.severity}">${f.severity}</span>${esc(f.title)}</h3><p>${esc(f.evidence)}</p><p><b>Διόρθωση:</b> ${esc(f.recommendation)}</p></article>`).join(''):'<p>Δεν εντοπίστηκαν προβλήματα από τους συγκεκριμένους παθητικούς ελέγχους.</p>';$('#aiText').textContent=r.ai?.text||r.ai?.error||'Δεν χρησιμοποιήθηκε AI. Πρόσθεσε OpenRouter API key στις Ρυθμίσεις.';$('#modelBadge').textContent=r.ai?.model||'OpenRouter'}
$('#exportBtn').onclick=async()=>{if(report)await window.vexon.exportReport(report)};
