// Uses only the isolated preload API; secrets never enter reports or localStorage.
const settingsView=document.querySelector('#settings');
const box=document.createElement('section');box.className='panel padded';box.innerHTML=`<h2>Αντίγραφα ασφαλείας & ενημερώσεις</h2><p>Κρυπτογραφημένο backup έργων, αναφορών και συνομιλιών. Τα API keys και τα cookies εξαιρούνται. Η εισαγωγή προσθέτει έργα χωρίς αντικατάσταση· χρειάζονται ξανά επιβεβαίωση άδειας.</p><label>Κωδικός backup (12+ χαρακτήρες)<input id="backupPassword" type="password" autocomplete="new-password"></label><button id="backupSave" class="secondary">Εξαγωγή backup</button> <button id="backupLoad" class="secondary">Εισαγωγή backup</button> <button id="checkUpdates" class="secondary">Έλεγχος ενημερώσεων</button><p id="upgradeState" role="status"></p>`;settingsView.append(box);
const error=e=>toast(e.message,true);
document.querySelector('#backupSave').onclick=async()=>{try{const file=await window.vexon.backupExport(document.querySelector('#backupPassword').value);if(file)toast('Αποθηκεύτηκε κρυπτογραφημένο backup.');}catch(e){error(e);}finally{document.querySelector('#backupPassword').value='';}};
document.querySelector('#backupLoad').onclick=async()=>{try{const n=await window.vexon.backupImport(document.querySelector('#backupPassword').value);if(n!==null){await refresh();toast('Εισήχθησαν '+n+' έργα. Έλεγξε τις ρυθμίσεις και την άδεια πριν σάρωση.');}}catch(e){error(e);}finally{document.querySelector('#backupPassword').value='';}};
document.querySelector('#checkUpdates').onclick=async()=>{try{const r=await window.vexon.updates();document.querySelector('#upgradeState').textContent=r.message||r.status;}catch(e){error(e);}};
const form=document.querySelector('#projectForm');const extras=document.createElement('div');extras.innerHTML='<label class="checkbox"><input name="wordpress" type="checkbox"> Απογραφή WordPress και αναζήτηση CVE (έως 5 στοιχεία)</label><label class="checkbox"><input name="cveWatch" type="checkbox"> Καθημερινή παρακολούθηση CVE στην τελευταία απογραφή εξαρτήσεων όσο λειτουργεί η εφαρμογή</label>';form.querySelector('.authorization').before(extras);
const controls=document.createElement('div');controls.className='panel padded';controls.innerHTML=`<h2>Προσωρινή σύνδεση & παρακολούθηση</h2><p>Αφορά την ιστοσελίδα που έχεις επιλέξει στο chat. Για σύνδεση επικόλλησε Cookie header από δοκιμαστικό λογαριασμό. Ισχύει έως 1 ώρα στη μνήμη, μόνο σε χειροκίνητους ελέγχους HTTPS στο ίδιο origin. Η εφαρμογή δεν επιβεβαιώνει αυτόματα ότι η συνεδρία είναι ενεργή.</p><label>Cookie header<input id="sessionCookie" type="password" autocomplete="off" placeholder="session=..."></label><button id="sessionSave" class="secondary">Χρήση συνεδρίας</button> <button id="sessionClear" class="subtle">Διαγραφή συνεδρίας</button> <button id="watchNow" class="secondary">Έλεγχος νέων CVE τώρα</button><pre id="watchResult"></pre>`;document.querySelector('#chat').append(controls);
const projectId=()=>{const id=document.querySelector('#chatProject').value;if(!id)throw new Error('Επίλεξε ιστοσελίδα στο chat.');return id;};
document.querySelector('#sessionSave').onclick=async()=>{try{await window.vexon.session(projectId(),document.querySelector('#sessionCookie').value);toast('Προσωρινή συνεδρία ενεργή για έως 1 ώρα.');}catch(e){error(e);}finally{document.querySelector('#sessionCookie').value='';}};
document.querySelector('#sessionClear').onclick=async()=>{try{await window.vexon.session(projectId(),'');toast('Η συνεδρία διαγράφηκε.');}catch(e){error(e);}};
document.querySelector('#watchNow').onclick=async()=>{const output=document.querySelector('#watchResult');try{output.textContent='Έλεγχος OSV…';const result=await window.vexon.watch(projectId());output.textContent=`${result.checked} εξαρτήσεις · ${result.matches.length} αντιστοιχίσεις · ${result.new.length} νέες από τον προηγούμενο έλεγχο.\nΑπογραφή: ${date(result.inventoryAt)}\n`+result.new.map(x=>`${x.ecosystem}: ${x.name}@${x.version} → ${x.advisory}`).join('\n');}catch(e){output.textContent=e.message;}};
const livePanel=document.createElement('div');livePanel.className='chat-help';livePanel.hidden=true;document.querySelector('#chatMessages').before(livePanel);const events=new Map();window.vexon.onProgress(p=>{if(!p.projectId)return;const list=p.stage==='start'?[]:(events.get(p.projectId)||[]);list.push(`${new Date().toLocaleTimeString('el-GR')} · ${p.message}`);events.set(p.projectId,list.slice(-15));if(document.querySelector('#chatProject').value===p.projectId){livePanel.hidden=false;livePanel.textContent=list.slice(-4).join(' → ');}});
const originalRender=renderReport;renderReport=function(report){originalRender(report);const extra=document.createElement('section');extra.className='panel padded';extra.innerHTML=`<h2>Αποδείξεις & προτεινόμενες αλλαγές</h2><button class="secondary" id="exportProposal">Λήψη πρότασης ρυθμίσεων</button><p>Οι προτάσεις για υποστηριζόμενα headers εξάγονται για έλεγχο σε staging πριν εφαρμογή.</p><h3>Σύγκριση πριν / μετά</h3>${(report.evidenceDiff||[]).map(d=>`<details><summary>${esc(d.title)} · ${esc(statusLabel[d.state]||d.state)}</summary><p><b>Πριν:</b> ${esc(d.before||'Δεν καταγράφηκε')}</p><p><b>Μετά:</b> ${esc(d.after||'Δεν καταγράφηκε — έλεγξε την κάλυψη')}</p></details>`).join('')||'<p>Δεν υπάρχει διαθέσιμη σύγκριση.</p>'}<h3>WordPress: ορατά στοιχεία</h3>${(report.wordpress||[]).map(c=>`<p>${esc(c.type)} · ${esc(c.slug)} · ${esc(c.version||'Άγνωστη έκδοση')} · Ένδειξη που χρειάζεται επιβεβαίωση</p>`).join('')||'<p>Δεν εντοπίστηκαν ορατά στοιχεία. Η απουσία δεν αποκλείει WordPress.</p>'}${(report.wordpressResearch||[]).map(researchHtml).join('')}<h3>Βεβαιότητα ευρημάτων</h3>${report.findings.map(f=>`<p><b>${esc(f.title)}</b> — ${esc(f.confirmation||'Χρειάζεται αξιολόγηση.')}</p>`).join('')}`;document.querySelector('#reportContent').append(extra);document.querySelector('#exportProposal').onclick=async()=>{try{if(await window.vexon.remediation(report.id))toast('Αποθηκεύτηκε πρόταση. Δεν εφαρμόστηκαν αλλαγές.');}catch(e){error(e);}};};
