const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabels={open:'Ανοιχτό',resolved:'Διορθώθηκε',needs_verification:'Χρειάζεται επιβεβαίωση',complete:'Ολοκληρώθηκε',partial:'Μερική κάλυψη',failed:'Απέτυχε',cancelled:'Ακυρώθηκε'};
const kindLabels={observed:'Παρατηρήθηκε',recommendation:'Σύσταση',needs_confirmation:'Πιθανό πρόβλημα - επιβεβαίωση'};
function reportHtml(report,project={},brand={}){
  const logo=/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(brand.logo||'')?`<img src="${brand.logo}" alt="Λογότυπο">`:'';
  const all=[...report.findings,...(report.resolved||[])];
  const item=f=>`<article><div class="tag">${escape(f.severity.toUpperCase())} · ${escape(kindLabels[f.kind]||f.kind)} · ${escape(statusLabels[f.status])}</div><h3>${escape(f.title)}</h3><p class="url">${escape(f.url)}</p><p><b>Απόδειξη:</b> ${escape(f.evidence)}</p><p><b>Ενέργεια:</b> ${escape(f.recommendation)}</p>${f.vulnerability?`<p><b>CVE:</b> ${escape(f.vulnerability.cves.join(", ")||"Δεν παρέχεται alias")}<br><b>CVSS:</b> ${escape(f.vulnerability.cvss.join("; ")||"Δεν παρέχεται")}<br>Αντιστοίχιση έκδοσης εξάρτησης · ${escape(f.vulnerability.source)}</p>`:""}</article>`;
  return `<!doctype html><html lang="el"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:"><style>
  @page{size:A4;margin:18mm 16mm 20mm}*{box-sizing:border-box}body{font:11px 'Segoe UI',Arial,sans-serif;color:#203047;line-height:1.55;margin:0}header{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #13a88c;padding-bottom:18px;margin-bottom:28px}header img{max-width:140px;max-height:60px}small,.muted{color:#657389}h1{font-size:30px;color:#12263d;line-height:1.2;margin:8px 0}h2{font-size:17px;margin:24px 0 12px}h3{font-size:13px;margin:6px 0}.meta{background:#edf5f7;border-radius:9px;padding:18px;margin:20px 0}.score{font-size:32px;color:#087d6a}.grid{display:flex;gap:28px}article{border:1px solid #d7e1e8;border-left:4px solid #18a88d;padding:13px 16px;margin:0 0 12px;break-inside:avoid}.tag{font-size:9px;font-weight:700;color:#346479}.url,p{overflow-wrap:anywhere;word-break:break-word}.url{color:#586c81;font-size:10px}p{margin:6px 0}.note{background:#fff5e4;padding:12px;border:1px solid #e9d5b6;break-inside:avoid}pre{white-space:pre-wrap;font:11px 'Segoe UI',Arial,sans-serif;overflow-wrap:anywhere}.ai{page-break-before:always}li{margin:5px 0}footer{margin-top:24px;color:#657389;font-size:9px}</style></head><body>
  <header><div><b>${escape(brand.company||'VEXON')}</b><br><small>WEBSITE SECURITY REVIEW</small></div>${logo}</header>
  <small>ΑΝΑΦΟΡΑ ΑΣΦΑΛΕΙΑΣ · ${escape(report.id||'PREVIEW')}</small><h1>${escape(project.name||'Έλεγχος ιστοσελίδας')}</h1><p>${escape(project.client||'')} · ${escape(report.target)}</p>
  <div class="meta"><div class="grid"><div><div class="score">${report.summary.score??'—'}${report.summary.score===null?'':' / 100'}</div><small>Ενδεικτική βαθμολογία ρυθμίσεων</small></div><div><b>${escape(statusLabels[report.status]||report.status)}</b><p>${report.pagesScanned.length} επιτυχημένες σελίδες · ${report.summary.total} ευρήματα</p><p>${escape(new Date(report.completedAt).toLocaleString('el-GR'))}</p></div></div></div>
  <div class="note">Η βαθμολογία δεν πιστοποιεί ασφάλεια. Η μερική ή αποτυχημένη σάρωση δεν λαμβάνει βαθμολογία. Οι συστάσεις και τα πιθανά προβλήματα διακρίνονται από όσα παρατηρήθηκαν άμεσα.</div>
  <h2>Κάλυψη & σύγκριση</h2><p>${escape(report.methodology)}</p><p>${report.comparison?.new||0} νέα · ${report.comparison?.resolved||0} διορθώθηκαν · ${report.comparison?.unverified||0} χρειάζονται επανέλεγχο</p><p>TLS: ${escape(report.tls?.validTo||'Δεν καταγράφηκε ημερομηνία λήξης')} · Browser: ${report.browser?.pages?.length||0} σελίδες · Κώδικας: ${report.source?.filesChecked||0} αρχεία / ${report.source?.packagesChecked||0} npm πακέτα</p>
  ${report.errors.length?'<h2>Περιορισμοί / σφάλματα</h2><ul>'+report.errors.map(e=>'<li>'+escape(e.module)+': '+escape(e.error)+'</li>').join('')+'</ul>':''}
  <h2>Ευρήματα & οδηγίες διόρθωσης</h2>${all.length?all.map(item).join(''):'<p>Δεν προέκυψαν ευρήματα από τους ελέγχους που ολοκληρώθηκαν. Αυτό δεν αποκλείει άλλες ευπάθειες.</p>'}
  ${(report.cveCandidates||[]).length?'<h2>Υποψήφιες αναφορές NVD</h2><p>Αποτελέσματα διαδικτυακής αναζήτησης, χωρίς επιβεβαίωση ότι η ιστοσελίδα επηρεάζεται.</p>'+report.cveCandidates.map(r=>'<h3>'+escape(r.query)+'</h3>'+r.items.map(v=>'<article><b>'+escape(v.id)+' · CVSS '+escape(v.score??'—')+'</b><p>'+escape(v.description)+'</p><p>'+escape(v.source)+'</p></article>').join('')).join(''):''}
  ${report.ai?.text?'<section class="ai"><h2>Συμπληρωματική AI ανάλυση</h2><p class="muted">Απαιτεί ανθρώπινη αξιολόγηση. Δεν μεταβάλλει τα τεχνικά ευρήματα.</p><pre>'+escape(report.ai.text)+'</pre></section>':''}
  <footer>${escape(brand.company||'Vexon')} · ${escape(brand.contact||'')} · Δημιουργήθηκε από Vexon Security Scanner 3</footer></body></html>`;
}
module.exports={reportHtml,escape,statusLabels,kindLabels};
